# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: lint-test-build

on: [push, pull_request]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 'Create env for backend'
        run: |
          cd backend
          touch .env
          echo "DATABASE_URL=postgresql://prisma:prisma@localhost:5433/tests" >> .env
      - name: Install all dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd backend && npm ci
      - name: Lint files
        run: |
          npx lint-staged
          npm run lint:frontend
          npm run lint:backend
      - name: Run unit tests
        run: |
          npm run test:frontend
          npm run test-unit:backend
      - name: Build project
        run: |
          npm run build:frontend
          npm run build:backend
